export const LOCALE_CONFIG = {
  pt: { locale: "pt-BR", currency: "BRL" },
  en: { locale: "en-US", currency: "USD" },
  es: { locale: "es-ES", currency: "EUR" },
};

export const UI_COPY = {
  pt: {
    languageName: "Português",
    menuTitle: "Menu",
    close: "Fechar",
    nav: {
      problema: "Problema",
      solucao: "Solução",
      como: "Como funciona",
      beneficios: "Benefícios",
      precos: "Porque Hive",
      faq: "Demo",
    },
    buttons: {
      headerCta: "Agendar demonstração gratuita",
      heroPrimary: "Agendar demonstração gratuita",
      heroSecondary: "Ver a solução em detalhes",
      roiValidate: "Quero validar esta simulação",
      viewEntry: "Ver formato de entrada",
      contactConsultant: "Falar com consultor",
      formPrimary: "Quero receber um diagnóstico comercial",
      formSecondary: "Ver planos primeiro",
      mobileCta: "Agendar demonstração",
      backToTop: "Topo",
      openMenu: "Menu",
      toggleTheme: "Tema",
      copySummary: "Copiar resumo",
      copied: "Copiado",
    },
    hero: {
      eyebrow:
        "Nova geração de conciliação bancária para escritórios contábeis",
      titleBefore: "Transforme a conciliação em uma",
      titleAccent: "máquina de margem",
      titleAfter: "não em um gargalo operacional.",
      sub: "A Hive automatiza o cruzamento entre contabilidade e extratos, destaca exceções com prioridade e entrega um dashboard claro para o time fechar mais rápido, com menos erro e mais previsibilidade.",
      bullets: [
        "Reduz tempo manual e retrabalho em tarefas repetitivas",
        "Mostra pendências e divergências em uma única visão",
        "Padroniza decisões com regras para escalar a operação",
        "Implementação por piloto para provar ROI antes de expandir",
      ],
      micro: "Demonstração rápida (15 min) • Sem compromisso • Foco no seu fluxo real",
      metrics: [
        { value: "15 min", label: "Demonstração objetiva" },
        { value: "Piloto", label: "Entrada com baixo risco" },
        { value: "ROI", label: "Diagnóstico orientado a margem" },
      ],
      panelTitle: "Hive Command Center",
      today: "Hoje",
      conciliated: "Conciliado",
      pendingCritical: "Pendências críticas",
      prioritized: "Priorizadas por impacto",
      vsManual: "+18% vs. fluxo manual",
    },
    offer: { entryOffer: "Oferta de entrada", guidedPilot: "Piloto guiado" },
    proofChip: {
      conversion: "Foco em conversão",
      conversionText:
        "Copy e layout estruturados para levar o visitante do problema ao diagnóstico.",
      ready: "Pronto para vender",
      readyText:
        "CTAs distribuídos, objeções tratadas e narrativa orientada a ROI.",
    },
    mobileCta: {
      title: "Agendar demonstração gratuita",
      subtitle: "Descubra quanto tempo pode poupar",
    },
    theme: { light: "Modo claro", dark: "Modo escuro" },
    language: { label: "Idioma" },
    footer: {
      subtitle: "Conciliação automática para operações contábeis",
      copyright: "© BeeFirst • Hive",
    },
    closing: {
      badge: "Próximo passo",
      title:
        "Agende um diagnóstico e descubra onde a sua operação está perdendo margem hoje.",
      description:
        "Em 15 minutos, mapeamos o fluxo atual, mostramos onde a Hive gera impacto e desenhamos uma proposta de piloto alinhada ao seu volume e equipa.",
      bullets: [
        "Sem compromisso de contratação no primeiro contato",
        "Diagnóstico orientado a ROI, não só demo técnica",
        "Plano de entrada para validar ganho antes de expandir",
      ],
      cardBadge: "Diagnóstico comercial",
      cardMeta: "15 min",
      noteIdle:
        "Preencha e use este bloco como captura de lead. Você pode conectar ao Calendly, CRM ou WhatsApp.",
      noteSuccess:
        "Pedido recebido. Próximo passo: conecte este formulário ao seu CRM/Calendly para capturar leads reais.",
      form: {
        name: "Nome",
        namePlaceholder: "Seu nome",
        email: "Email",
        emailPlaceholder: "voce@empresa.com",
        company: "Empresa",
        companyPlaceholder: "Nome do escritório",
        profile: "Perfil",
        profileOptions: {
          escritorio: "Escritório contábil",
          bpo: "BPO financeiro",
          financeiro: "Financeiro interno",
          outro: "Outro",
        },
        volume: "Volume mensal (estimado)",
        volumeOptions: {
          baixo: "Até 10 clientes / contas",
          medio: "11 a 50 clientes / contas",
          alto: "51 a 150 clientes / contas",
          enterprise: "150+ clientes / contas",
        },
        goal: "Principal objetivo",
        goalPlaceholder:
          "Ex.: reduzir horas de conciliação, ganhar visibilidade, escalar a equipa sem contratar",
      },
      mini: {
        format: "Formato",
        formatValue: "Chamada online",
        output: "Saída",
        outputValue: "Plano de piloto + próximos passos",
        time: "Tempo",
        timeValue: "15 minutos",
        focus: "Foco",
        focusValue: "Diagnóstico orientado a ROI",
      },
    },
    drawer: {
      title: "Navegação rápida",
      subtitle: "Acesse seções, altere idioma e mude o tema.",
      primary: "Agendar demonstração gratuita",
      secondary: "Porque Hive",
    },
    ui: {
      scrollProgress: "Progresso de leitura",
      themeToggleAria: "Alternar modo claro/escuro",
      langSwitcherAria: "Selecionar idioma",
      mobileMenuAria: "Abrir menu mobile",
      closeMenuAria: "Fechar menu mobile",
    },
  },
  en: {
    languageName: "English",
    menuTitle: "Menu",
    close: "Close",
    nav: {
      problema: "Problem",
      solucao: "Solution",
      como: "How it works",
      beneficios: "Benefits",
      precos: "Plans",
      faq: "FAQ",
    },
    buttons: {
      headerCta: "Book assessment",
      heroPrimary: "I want a commercial assessment",
      heroSecondary: "See the solution in detail",
      roiValidate: "Validate this estimate",
      viewEntry: "See entry format",
      contactConsultant: "Talk to consultant",
      formPrimary: "Request a commercial assessment",
      formSecondary: "See plans first",
      mobileCta: "Book",
      backToTop: "Top",
      openMenu: "Menu",
      toggleTheme: "Theme",
      copySummary: "Copy summary",
      copied: "Copied",
    },
    hero: {
      eyebrow: "Next-generation bank reconciliation for accounting firms",
      titleBefore: "Turn reconciliation into a",
      titleAccent: "margin machine",
      titleAfter: "instead of an operational bottleneck.",
      sub: "Hive automates matching between accounting records and bank statements, prioritizes exceptions, and gives your team a clear dashboard to close faster with fewer errors.",
      bullets: [
        "Cuts manual time and repetitive rework",
        "Shows pending items and mismatches in one view",
        "Standardizes decisions with reusable rules",
        "Pilot-first rollout to prove ROI before expansion",
      ],
      micro: "Fast demo (15 min) • No commitment • Focused on your actual workflow",
      metrics: [
        { value: "15 min", label: "Objective demo" },
        { value: "Pilot", label: "Low-risk start" },
        { value: "ROI", label: "Margin-oriented assessment" },
      ],
      panelTitle: "Hive Command Center",
      today: "Today",
      conciliated: "Matched",
      pendingCritical: "Critical pending",
      prioritized: "Prioritized by impact",
      vsManual: "+18% vs manual flow",
    },
    offer: { entryOffer: "Entry offer", guidedPilot: "Guided pilot" },
    proofChip: {
      conversion: "Conversion focus",
      conversionText:
        "Copy and layout are structured to move visitors from pain point to assessment.",
      ready: "Sales-ready",
      readyText:
        "Distributed CTAs, handled objections and ROI-driven narrative.",
    },
    mobileCta: { title: "Want to validate Hive ROI?", subtitle: "Book a 15-min assessment" },
    theme: { light: "Light mode", dark: "Dark mode" },
    language: { label: "Language" },
    footer: {
      subtitle: "Automated reconciliation for accounting operations",
      copyright: "© BeeFirst • Hive",
    },
    closing: {
      badge: "Next step",
      title:
        "Book an assessment and discover where your operation is losing margin today.",
      description:
        "In 15 minutes, we map your current flow, show where Hive creates impact, and outline a pilot plan aligned to your volume and team.",
      bullets: [
        "No commitment in the first call",
        "ROI-oriented assessment, not just a technical demo",
        "Pilot-first rollout to validate gains before expansion",
      ],
      cardBadge: "Commercial assessment",
      cardMeta: "15 min",
      noteIdle:
        "Use this as your lead capture block. Connect it to Calendly, CRM or WhatsApp.",
      noteSuccess:
        "Request received. Next step: connect this form to your CRM/Calendly to capture real leads.",
      form: {
        name: "Name",
        namePlaceholder: "Your name",
        email: "Email",
        emailPlaceholder: "you@company.com",
        company: "Company",
        companyPlaceholder: "Firm name",
        profile: "Profile",
        profileOptions: {
          escritorio: "Accounting firm",
          bpo: "Financial BPO",
          financeiro: "In-house finance",
          outro: "Other",
        },
        volume: "Monthly volume (estimate)",
        volumeOptions: {
          baixo: "Up to 10 clients / accounts",
          medio: "11 to 50 clients / accounts",
          alto: "51 to 150 clients / accounts",
          enterprise: "150+ clients / accounts",
        },
        goal: "Main goal",
        goalPlaceholder:
          "E.g.: reduce reconciliation hours, gain visibility, scale the team without hiring",
      },
      mini: {
        format: "Format",
        formatValue: "Online call",
        output: "Outcome",
        outputValue: "Pilot plan + next steps",
        time: "Time",
        timeValue: "15 minutes",
        focus: "Focus",
        focusValue: "ROI-oriented assessment",
      },
    },
    drawer: {
      title: "Quick navigation",
      subtitle: "Jump to sections, switch language and theme.",
      primary: "Book assessment",
      secondary: "Go to plans",
    },
    ui: {
      scrollProgress: "Reading progress",
      themeToggleAria: "Toggle light/dark mode",
      langSwitcherAria: "Select language",
      mobileMenuAria: "Open mobile menu",
      closeMenuAria: "Close mobile menu",
    },
  },
  es: {
    languageName: "Español",
    menuTitle: "Menú",
    close: "Cerrar",
    nav: {
      problema: "Problema",
      solucao: "Solución",
      como: "Cómo funciona",
      beneficios: "Beneficios",
      precos: "Planes",
      faq: "FAQ",
    },
    buttons: {
      headerCta: "Agendar diagnóstico",
      heroPrimary: "Quiero un diagnóstico comercial",
      heroSecondary: "Ver la solución en detalle",
      roiValidate: "Validar esta simulación",
      viewEntry: "Ver formato de entrada",
      contactConsultant: "Hablar con consultor",
      formPrimary: "Quiero un diagnóstico comercial",
      formSecondary: "Ver planes primero",
      mobileCta: "Agendar",
      backToTop: "Arriba",
      openMenu: "Menú",
      toggleTheme: "Tema",
      copySummary: "Copiar resumen",
      copied: "Copiado",
    },
    hero: {
      eyebrow:
        "Nueva generación de conciliación bancaria para despachos contables",
      titleBefore: "Convierte la conciliación en una",
      titleAccent: "máquina de margen",
      titleAfter: "y no en un cuello de botella operativo.",
      sub: "Hive automatiza el cruce entre contabilidad y extractos, prioriza excepciones y entrega un dashboard claro para cerrar más rápido con menos errores.",
      bullets: [
        "Reduce tiempo manual y retrabajo",
        "Muestra pendientes y divergencias en una sola vista",
        "Estandariza decisiones con reglas reutilizables",
        "Implementación por piloto para validar ROI",
      ],
      micro: "Demo rápida (15 min) • Sin compromiso • Foco en tu flujo real",
      metrics: [
        { value: "15 min", label: "Demo objetiva" },
        { value: "Piloto", label: "Entrada de bajo riesgo" },
        { value: "ROI", label: "Diagnóstico orientado al margen" },
      ],
      panelTitle: "Hive Command Center",
      today: "Hoy",
      conciliated: "Conciliado",
      pendingCritical: "Pendientes críticos",
      prioritized: "Priorizados por impacto",
      vsManual: "+18% vs. flujo manual",
    },
    offer: { entryOffer: "Oferta de entrada", guidedPilot: "Piloto guiado" },
    proofChip: {
      conversion: "Enfoque de conversión",
      conversionText:
        "Copy y layout diseñados para llevar al visitante del problema al diagnóstico.",
      ready: "Listo para vender",
      readyText:
        "CTAs distribuidos, objeciones tratadas y narrativa orientada a ROI.",
    },
    mobileCta: {
      title: "¿Quieres validar el ROI de Hive?",
      subtitle: "Agenda un diagnóstico de 15 min",
    },
    theme: { light: "Modo claro", dark: "Modo oscuro" },
    language: { label: "Idioma" },
    footer: {
      subtitle: "Conciliación automática para operaciones contables",
      copyright: "© BeeFirst • Hive",
    },
    closing: {
      badge: "Siguiente paso",
      title:
        "Agenda un diagnóstico y descubre dónde tu operación pierde margen hoy.",
      description:
        "En 15 minutos mapeamos tu flujo actual, mostramos dónde Hive genera impacto y diseñamos un piloto alineado con tu volumen y equipo.",
      bullets: [
        "Sin compromiso de contratación en el primer contacto",
        "Diagnóstico orientado a ROI, no solo demo técnica",
        "Plan de entrada para validar valor antes de escalar",
      ],
      cardBadge: "Diagnóstico comercial",
      cardMeta: "15 min",
      noteIdle:
        "Usa este bloque como captura de leads. Puedes conectarlo con Calendly, CRM o WhatsApp.",
      noteSuccess:
        "Solicitud recibida. Próximo paso: conecta este formulario a tu CRM/Calendly para captar leads reales.",
      form: {
        name: "Nombre",
        namePlaceholder: "Tu nombre",
        email: "Email",
        emailPlaceholder: "tu@empresa.com",
        company: "Empresa",
        companyPlaceholder: "Nombre del despacho",
        profile: "Perfil",
        profileOptions: {
          escritorio: "Despacho contable",
          bpo: "BPO financiero",
          financeiro: "Finanzas internas",
          outro: "Otro",
        },
        volume: "Volumen mensual (estimado)",
        volumeOptions: {
          baixo: "Hasta 10 clientes / cuentas",
          medio: "11 a 50 clientes / cuentas",
          alto: "51 a 150 clientes / cuentas",
          enterprise: "150+ clientes / cuentas",
        },
        goal: "Objetivo principal",
        goalPlaceholder:
          "Ej.: reducir horas de conciliación, ganar visibilidad, escalar el equipo sin contratar",
      },
      mini: {
        format: "Formato",
        formatValue: "Llamada online",
        output: "Salida",
        outputValue: "Plan de piloto + próximos pasos",
        time: "Tiempo",
        timeValue: "15 minutos",
        focus: "Foco",
        focusValue: "Diagnóstico orientado a ROI",
      },
    },
    drawer: {
      title: "Navegación rápida",
      subtitle: "Accede a secciones, cambia idioma y tema.",
      primary: "Agendar diagnóstico",
      secondary: "Ir a planes",
    },
    ui: {
      scrollProgress: "Progreso de lectura",
      themeToggleAria: "Cambiar modo claro/oscuro",
      langSwitcherAria: "Seleccionar idioma",
      mobileMenuAria: "Abrir menú móvil",
      closeMenuAria: "Cerrar menú móvil",
    },
  },
};
